---
stages:
- build
- release
- canary

# Build the Go application
build:
  stage: build
  image: golang:1.24.2
  artifacts:
    paths:
      - backendify
      - config.json
  script:
    - go mod download
    - go test ./...
    - go build -o backendify ./cmd

###################################################
## do not remove or edit this block, it is
## required for us to accept your submission!
release:
  stage: release
  image: docker:stable
  services:
  - docker:dind
  before_script:
  - until docker version ; do sleep 1; done
  - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
  - docker build --pull -t ${CI_REGISTRY_IMAGE} .
  - docker push ${CI_REGISTRY_IMAGE}

canary:
  stage: canary
  image: registry.gitlab.com/autoiterativesolutions/src/monolith/ais-client:master
  script: [ "/usr/bin/ais-client" ]
##
###################################################
